[tool.poetry]
name = "nba-statistics"
version = "0.1.0"
description = ""
authors = ["Louis Duvieux <lduvieux@laposte.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
dbt = "^1.0.0.34.14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
