
version: 2

models:
  - name: dim_player_infos
    description: "Dim model for players"
    columns:
      - name: team_code
        description: "The primary key for this view"
        tests:
          - unique
          - not_null

  - name: dim_team_infos
    description: "Dim model for teams"
    columns:
      - name: player_fullname
        description: "The primary key for this view"
        tests:
          - unique
          - not_null

  - name: fact_player_logs
    description: "Fact table by game and player"
    columns:
      - name: player_fullname
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: fact_team_logs
    description: "Fact table by game and team"
    columns:
      - name: team
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
